### ISSUE TITLE
Detecting socket disconnect

### ISSUE THREAD

**Issue by devpro555** [obrunsmann/flutter_nakama#23]
Hello,

I am running into an issue where the user gets disconnected from the socket either due to idle time or server error. I am not able to find a way to detect that the socket connection is lost and make an attempt to reconnect.
Can you let me know how and where to listen for socket disconnect event and can I simply reconnect using the same NakamaWebsocketClient.init method at that point?

**Comment by obrunsmann** [comment]
The problem we imo have in the Flutter package is that we need to support both REST and gRPC in parallel due to web + native support.
This means we need a unified way of handling errors and exceptions which are valid equally for REST and gRPC.


What you could do in the meantime is the following:

```dart
try {
  await nakama.authenticateEmail(email: 'foo@bar.de', password: 'xxxxxx');
} on GrpcError catch (e) {
  if(e.code == StatusCode.unavailable) {
    // no connection?
  }
}
```


Currently, due to the lack of an error concept for this package, the package does not handle the gRPC exceptions so you can handle them on your own just as needed.

**Comment by devpro555** [comment]
Thanks for the reply, another thing that I need to understand is that when logging off the user I call NakamaWebsocketClient.instance.close(); but when I login again the socket doesn't connect and I receive messages in console that the data cannot be sent after the connection is closed. How should I reconnect?

**Comment by AxiatCode** [comment]
> Thanks for the reply, another thing that I need to understand is that when logging off the user I call NakamaWebsocketClient.instance.close(); but when I login again the socket doesn't connect and I receive messages in console that the data cannot be sent after the connection is closed. How should I reconnect?

@obrunsmann Can you please look into this, we need to resolve this as we are working on our client's commercial project with a multiplayer game.

Thanks for the co-operation.

**Comment by wentao** [comment]
Is this issue being fixed in the current release?

**Comment by obrunsmann** [comment]
Hey Guys :) Sorry for my very late reply; currently I am a little limited in time, so that I unfortunately had to neglect the package. I created `onError` and `onDone` methods for the websocket client.

@AxiatCode FYI I changed the naming of the method from `onDoneCallback` to `onDone`, sounds better for me. Should be naturally that a closure is a callback :)
