### ISSUE TITLE
Methods in  NakamaGrpcClient   lack of  options

### ISSUE THREAD

**Issue by adaixiaoshuai** [obrunsmann/flutter_nakama#61]
**Describe the bug**
 grpc ：invalid token 

**Reproduction Code**
     options: _getSessionCallOptions(session),

Example:
```dart
   Future<model.FriendsList> listFriends({
    required model.Session session,
    FriendshipState? friendshipState,
    int limit = defaultLimit,
    String? cursor,
  }) async {
    final res = await _client.listFriends(
      api.ListFriendsRequest(
        cursor: cursor,
        limit: api.Int32Value(value: limit),
        state: api.Int32Value(value: friendshipState?.index),
      ),
    );

    return model.FriendsList.fromDto(res);
  }
```

**Expected behavior**

**Screenshots**

**Flutter Doctor**

```

```

**pubspec.yaml**

```yaml

```

**Additional context**

**Comment by obrunsmann** [comment]
Thank you for creating an issue. I appreciate your feedback. However, I would like to remind you that we have a designated issue template to ensure that all necessary information is provided in a structured manner. This helps us better understand and address the problem you're facing.

Could you please provide the missing details or follow the issue template by editing your original post? Including relevant information such as the steps to reproduce the issue, the expected behavior, and any error messages would greatly assist us in resolving the problem efficiently.

Once you've updated the issue with the required information, I'll be more than happy to assist you further. Thank you for your understanding.
